name: Docker Image CI - Backend

# This workflow will build a Docker image and push it to Azure Container Registry
# It is triggered on push or pull request to the main branch

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: aigbbemea.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: |
            aigbbemea.azurecr.io/visionarylab:${{ github.run_number }}
            aigbbemea.azurecr.io/visionarylab:latest
