name: Docker Image CI - Frontend

# This workflow will build a Docker image and push it to Azure Container Registry
# It is triggered on push or pull request to the main branch

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: dpcvoltvision.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            dpcvoltvision.azurecr.io/visionarylab-frontend:${{ github.run_number }}
            dpcvoltvision.azurecr.io/visionarylab-frontend:latest
